###

# curl --verbose --location --request POST 'localhost:8080/shop-orders'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "articleOrders": [
#        {
#            "articleId": 3,
#            "amount": 2
#        },
#        {
#            "articleId": 4,
#            "amount": 3
#        }
#    ]
#}'
POST localhost:8080/shop-orders
Content-Type: application/json

{
  "articleOrders": [
    {
      "articleId": 1,
      "amount": 2
    },
    {
      "articleId": 2,
      "amount": 3
    }
  ]
}

###

