# curl --request GET
#  --url http://localhost:8080/shop-orders
#  --header 'Content-Type: application/json'
GET http://localhost:8080/shop-orders
Content-Type: application/json

###

# curl --verbose --location --request POST 'localhost:8080/shop-orders'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "articleOrders": [
#        {
#            "articleId": 3,
#            "amount": 2
#        },
#        {
#            "articleId": 4,
#            "amount": 3
#        }
#    ]
#}'
POST localhost:8080/shop-orders
Content-Type: application/json

{
  "articleOrders": [
    {
      "articleId": 1,
      "amount": 2
    },
    {
      "articleId": 2,
      "amount": 3
    }
  ]
}

###
# curl --request GET
#  --url http://localhost:8080/articles
#  --header 'Content-Type: application/json'
GET http://localhost:8080/articles
Content-Type: application/json

###
# curl --request POST
#  --url http://localhost:8080/articles
#  --header 'Content-Type: application/json'
#  --data '{
#	"name": "Testartikel",
#	"price": 10.00
#}'
POST http://localhost:8080/articles
Content-Type: application/json

{
  "name": "Testartikel",
  "price": 10.00
}

###
# curl --request GET
#  --url http://localhost:8080/article-stocks
#  --header 'Content-Type: application/json'
GET http://localhost:8080/article-stocks
Content-Type: application/json

###
# curl --request PUT
#  --url http://localhost:8080/article-stocks/1
#  --header 'Content-Type: application/json'
#  --data '{
#	"count": 3
#}'
PUT http://localhost:8080/article-stocks/1
Content-Type: application/json

{
  "count": 3
}

###
# curl --location --request GET 'localhost:8080/chaos-monkey'
GET localhost:8080/chaos-monkey

###
# curl --location --request PUT 'localhost:8080/chaos-monkey/ArticleStockService'
#--header 'Content-Type: application/json'
#--data-raw '{
#        "enabled": true,
#        "errorRate": 0,
#        "latencyMs": 0,
#        "permitsPerSec": 0.5,
#        "rateLimiterType": "FAIL"
#    }
#'
PUT localhost:8080/chaos-monkey/ArticleStockService
Content-Type: application/json

{
  "enabled": true,
  "errorRate": 0,
  "latencyMs": 0,
  "permitsPerSec": 10,
  "rateLimiterType": "FAIL"
}


###



